/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


CREATE DATABASE /*!32312 IF NOT EXISTS*/ `sangit` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `sangit`;
DROP TABLE IF EXISTS `audio`;
CREATE TABLE `audio` (
  `id` int NOT NULL AUTO_INCREMENT,
  `DisplayName` text,
  `DisplayDescription` text,
  `TotalViews` int DEFAULT NULL,
  `WatchTime` time DEFAULT NULL,
  `Likes` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `audio_comments`;
CREATE TABLE `audio_comments` (
  `id` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `audio_id` int DEFAULT NULL,
  `commenText` text,
  PRIMARY KEY (`id`),
  KEY `audio_id` (`audio_id`),
  CONSTRAINT `audio_comments_ibfk_1` FOREIGN KEY (`audio_id`) REFERENCES `audio` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
